[tools]
"cargo:tauri-cli" = "latest"
"npm:vite" = "latest"

[tasks.setup]
description = "Install dependencies"
run = "bun install"

[tasks.dev]
description = "Run in dev mode"
run = "cargo tauri dev"

[tasks.build]
description = "Build"
run = "cargo tauri build"

[tasks.reset]
description = "Reset database"
run = "./reset"
